name: BingocraftCore
version: ${version}
main: com.pritam.bingocraft.plugin.BingocraftCore
loader: com.pritam.bingocraft.plugin.boot.BingocraftCoreLoader
description: Bingocraft-Core plugin.
authors:
  - Pritam
api-version: 1.21.7